version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: exeness-timescaledb
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : mypassword
      POSTGRES_DB : exeness
      POSTGRES_HOST_AUTH_METHOD : trust
    ports:
      -5432:5432
    volumes:
      -timescale-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - exeness-network
    restart: unless-stopped
  
  postgres:
    image: postgres:16-alpine
    container_name: exeness-postgres
    environment:
      POSTGRES_USER:postgres
      POSTGRES_PASSWORD:mypassword
      POSTGRES_DB:exeness
      POSTGRES_HOST_AUTH_METHOD:trust
    ports:
      - 5431:5432
    volumes:
      -postgres-data:/var/lib/postgre/data
    networks:
      - exeness-network
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: exeness-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - exeness-network
    restart: unless-stopped